### ISSUE TITLE
Add the verified dev logo to shields.io urls to make it look *n i c e* and *c o n s i s t e n t*

### ISSUE THREAD

**Issue by KarateWumpus** [ks00908/doot-doot#32]
Add this to the end of the end of a shields.io URL to add the verified dev badge as logo instead of just having it as an image because having it as an image makes me wanna cry
```?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+CiAgPHBhdGggZmlsbD0iIzNlNzBkZCIgZD0iTTIxLjU4IDExLjRMMTcuMyA0LjAxbC0uMzUtLjZINy4wNGwtLjM1LjYtNC4yNyA3LjM5LS4zNS42LjM1LjYgNC4yNyA3LjM5LjM1LjZoOS45MmwuMzUtLjYgNC4yOC03LjM5LjM1LS42LS4zNi0uNnpNOC41MSAxMC4zN0w2Ljg4IDEybDEuNjMgMS42M3YyLjczTDQuMTUgMTJsNC4zNy00LjM3djIuNzR6bTMuMTIgNi45M2wtMi4wNC0uNjMgMy4xLTkuOTggMi4wNC42NC0zLjEgOS45N3ptMy44Ni0uOTN2LTIuNzNMMTcuMTIgMTJsLTEuNjMtMS42M1Y3LjYzTDE5Ljg1IDEybC00LjM2IDQuMzd6Ii8+CiAgPHBhdGggZmlsbD0ibm9uZSIgZD0iTTAgMGgyNHYyNEgweiIvPgo8L3N2Zz4=```

**Comment by KarateWumpus** [comment]
So something like ```https://img.shields.io/badge/Verified%20bot%3F-Yes-brightgreen?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+CiAgPHBhdGggZmlsbD0iIzNlNzBkZCIgZD0iTTIxLjU4IDExLjRMMTcuMyA0LjAxbC0uMzUtLjZINy4wNGwtLjM1LjYtNC4yNyA3LjM5LS4zNS42LjM1LjYgNC4yNyA3LjM5LjM1LjZoOS45MmwuMzUtLjYgNC4yOC03LjM5LjM1LS42LS4zNi0uNnpNOC41MSAxMC4zN0w2Ljg4IDEybDEuNjMgMS42M3YyLjczTDQuMTUgMTJsNC4zNy00LjM3djIuNzR6bTMuMTIgNi45M2wtMi4wNC0uNjMgMy4xLTkuOTggMi4wNC42NC0zLjEgOS45N3ptMy44Ni0uOTN2LTIuNzNMMTcuMTIgMTJsLTEuNjMtMS42M1Y3LjYzTDE5Ljg1IDEybC00LjM2IDQuMzd6Ii8+CiAgPHBhdGggZmlsbD0ibm9uZSIgZD0iTTAgMGgyNHYyNEgweiIvPgo8L3N2Zz4=```
Would create this
![](https://img.shields.io/badge/Verified%20bot%3F-Yes-brightgreen?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+CiAgPHBhdGggZmlsbD0iIzNlNzBkZCIgZD0iTTIxLjU4IDExLjRMMTcuMyA0LjAxbC0uMzUtLjZINy4wNGwtLjM1LjYtNC4yNyA3LjM5LS4zNS42LjM1LjYgNC4yNyA3LjM5LjM1LjZoOS45MmwuMzUtLjYgNC4yOC03LjM5LjM1LS42LS4zNi0uNnpNOC41MSAxMC4zN0w2Ljg4IDEybDEuNjMgMS42M3YyLjczTDQuMTUgMTJsNC4zNy00LjM3djIuNzR6bTMuMTIgNi45M2wtMi4wNC0uNjMgMy4xLTkuOTggMi4wNC42NC0zLjEgOS45N3ptMy44Ni0uOTN2LTIuNzNMMTcuMTIgMTJsLTEuNjMtMS42M1Y3LjYzTDE5Ljg1IDEybC00LjM2IDQuMzd6Ii8+CiAgPHBhdGggZmlsbD0ibm9uZSIgZD0iTTAgMGgyNHYyNEgweiIvPgo8L3N2Zz4=)

**Comment by ks00908** [comment]
done, it honestly looks better, I just didn't knew how to use shields.io for custom badge lol
